name: Release

on:
  push:
    tags:
      - 'v*.*.*-custom'
      - 'v*.*.*-custom-r*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Build
      run: |
        GOOS=linux  GOARCH=amd64 make release REVISION=custom
        GOOS=darwin GOARCH=amd64 make release REVISION=custom
        GOOS=darwin GOARCH=arm64 make release REVISION=custom

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.tar.xz'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
